-- Dashboard sign-in (better-auth, see src/lib/dashboard-auth.ts): users, sessions,
-- password accounts, and the organization plugin's workspaces, members and
-- invitations. Generated by better-auth's migration compiler; column names are
-- the camelCase ones better-auth expects. A workspace's id is also its `orgs.id`.

create table "auth_user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "auth_session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "auth_user" ("id") on delete cascade, "activeOrganizationId" text);

create table "auth_account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "auth_user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "auth_verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "auth_organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" timestamptz not null, "metadata" text);

create table "auth_member" ("id" text not null primary key, "organizationId" text not null references "auth_organization" ("id") on delete cascade, "userId" text not null references "auth_user" ("id") on delete cascade, "role" text not null, "createdAt" timestamptz not null);

create table "auth_invitation" ("id" text not null primary key, "organizationId" text not null references "auth_organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "inviterId" text not null references "auth_user" ("id") on delete cascade);

create index "auth_session_userId_idx" on "auth_session" ("userId");
create index "auth_account_userId_idx" on "auth_account" ("userId");
create index "auth_verification_identifier_idx" on "auth_verification" ("identifier");
create index "auth_member_organizationId_idx" on "auth_member" ("organizationId");
create index "auth_member_userId_idx" on "auth_member" ("userId");
create index "auth_invitation_organizationId_idx" on "auth_invitation" ("organizationId");
create index "auth_invitation_email_idx" on "auth_invitation" ("email");
