// Every request in the Postman collection, grouped into folders. `bun run postman`
// turns this into offer-api.postman_collection.json, and test/postman.test.ts fails
// when a route in src/app.ts has no request here (or a request has no route).
//
// `path` is the route exactly as Hono registers it. Path params become collection
// variables ({{appId}}, {{accountId}}, …, see PARAM_VARIABLES in build.ts) unless
// `params` gives a literal value. `save` copies response fields into collection
// variables, so later requests pick them up.

export type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

/** Which key the request sends. Requests with "secret" inherit the collection's auth. */
export type Auth = "none" | "secret" | "public" | "token" | "admin";

export type RequestDef = {
  name: string;
  method: Method;
  path: string;
  auth: Auth;
  description?: string;
  params?: Record<string, string>;
  query?: { key: string; value: string; description?: string; disabled?: boolean }[];
  body?: unknown;
  /** Collection variable → dotted path in the JSON response, e.g. { appId: "id" }. */
  save?: Record<string, string>;
};

export type Folder = { name: string; description: string; requests: RequestDef[] };

const app = "/apps/:appId";
const account = `${app}/namespaces/:namespaceId`;

const KEYS = {
  secret: "Works with the secret key or the admin key.",
  public: "Works with the publishable key, the secret key or the admin key.",
  account: "Works with the publishable key, the account's own token, the secret key or the admin key.",
  token: "Works with the account's own token, the secret key or the admin key.",
  admin: "Admin key only. App keys get 401.",
};

export const FOLDERS: Folder[] = [
  {
    name: "Quickstart",
    description:
      "Run this folder top to bottom on an empty API (Collection Runner works). It creates an app, saves its keys into the collection variables, builds a Free and a Pro plan, creates an account, records usage and upgrades it. Every other folder then has data to work with.",
    requests: [
      {
        name: "Create an app",
        method: "POST",
        path: "/apps",
        auth: "none",
        description: "No key needed. Saves the app's id, secret key and publishable key into the collection variables.",
        body: { name: "My app" },
        save: { appId: "id", secretKey: "api_key", publicKey: "public_key" },
      },
      {
        name: "Create a usage entitlement",
        method: "POST",
        path: `${app}/entitlements`,
        auth: "secret",
        body: { id: "{{entitlementId}}", type: "usage", name: "Posts", description: "Posts an account can publish." },
      },
      {
        name: "Create the Free plan",
        method: "POST",
        path: `${app}/plans`,
        auth: "secret",
        body: { id: "{{freePlanId}}", name: "Free", isFree: true },
      },
      {
        name: "Give Free 3 posts",
        method: "POST",
        path: `${app}/plans/:planId/entitlements`,
        params: { planId: "{{freePlanId}}" },
        auth: "secret",
        body: { id: "{{entitlementId}}", max: 3 },
      },
      {
        name: "Create the Pro plan",
        method: "POST",
        path: `${app}/plans`,
        auth: "secret",
        body: {
          id: "{{planId}}",
          name: "Pro",
          pricingCard: { title: "Pro", type: "subscription", monthlyPrice: 29, yearlyPrice: 290, currency: "USD" },
        },
      },
      {
        name: "Give Pro 100 posts",
        method: "POST",
        path: `${app}/plans/:planId/entitlements`,
        auth: "secret",
        body: { id: "{{entitlementId}}", max: 100 },
      },
      {
        name: "Create an account on Free",
        method: "POST",
        path: `${app}/namespaces`,
        auth: "secret",
        body: { id: "{{accountId}}", name: "Ada Lovelace", plan: "{{freePlanId}}" },
      },
      {
        name: "Read the account's access",
        method: "GET",
        path: `${account}/full-plan`,
        auth: "public",
        description: `The plan with every entitlement resolved: usage, max, left and can. Sent with the publishable key, as a browser would. ${KEYS.account}`,
      },
      {
        name: "Record a post",
        method: "POST",
        path: `${account}/usage/:entitlementId/add`,
        auth: "public",
        description: `Adds 1 to the counter. ${KEYS.public}`,
      },
      {
        name: "Move the account to Pro",
        method: "PATCH",
        path: account,
        auth: "secret",
        description: "Changes the plan directly, without a payment. Use it for comps and support fixes.",
        body: { plan: "{{planId}}" },
      },
      {
        name: "Read the access again",
        method: "GET",
        path: `${account}/plan`,
        auth: "public",
        description: `Same as full-plan, with private meta keys removed. posts now has a max of 100. ${KEYS.account}`,
      },
    ],
  },
  {
    name: "Service",
    description: "Public routes with no key.",
    requests: [
      { name: "Banner", method: "GET", path: "/", auth: "none" },
      { name: "Health check", method: "GET", path: "/health", auth: "none", description: "Runs a query against Postgres. Render's health check." },
      { name: "OpenAPI document", method: "GET", path: "/openapi.json", auth: "none", description: "Covers the core routes only. This collection covers all of them." },
      { name: "API reference page", method: "GET", path: "/docs", auth: "none", description: "HTML. Open it in a browser." },
      { name: "Webhook event types", method: "GET", path: "/event-types", auth: "none", description: "Every event type with a sample data payload." },
    ],
  },
  {
    name: "Apps",
    description: "An app is one product you sell. Quickstart creates one; deleting it is in Clean up.",
    requests: [
      { name: "Get the app", method: "GET", path: app, auth: "secret" },
      {
        name: "Update the app",
        method: "PATCH",
        path: app,
        auth: "secret",
        description: "Merges fields. id, api_key, public_key and created_at are ignored.",
        body: { name: "My app", checkout_url: "https://example.com/checkout" },
      },
      {
        name: "Regenerate the secret key",
        method: "POST",
        path: `${app}/keys/regenerate`,
        auth: "secret",
        description: "Replaces the secret key and revokes every account token. Saves the new key.",
        save: { secretKey: "api_key" },
      },
      {
        name: "Regenerate the publishable key",
        method: "POST",
        path: `${app}/public-key/regenerate`,
        auth: "secret",
        save: { publicKey: "public_key" },
      },
    ],
  },
  {
    name: "Entitlements",
    description: "Things an account can use: usage (counted against a limit) or boolean (on or off).",
    requests: [
      { name: "List entitlements", method: "GET", path: `${app}/entitlements`, auth: "secret" },
      {
        name: "Create a boolean entitlement",
        method: "POST",
        path: `${app}/entitlements`,
        auth: "secret",
        description: 'A feature that is on or off. Quickstart already made the usage entitlement, posts; send type: "usage" for counted ones.',
        body: { id: "pin_posts", type: "boolean", name: "Pin posts" },
      },
      { name: "Get an entitlement", method: "GET", path: `${app}/entitlements/:entitlementId`, auth: "secret" },
      {
        name: "Block usage past the limit",
        method: "PATCH",
        path: `${app}/entitlements/:entitlementId`,
        auth: "secret",
        description: "With mode block, usage past the limit gets a 402 with an upgrade offer. offer_id is optional.",
        body: { overage: { mode: "block" } },
      },
    ],
  },
  {
    name: "Add-ons",
    description: "Named extras that plans, offers, incentives and accounts can include.",
    requests: [
      { name: "List add-ons", method: "GET", path: `${app}/addons`, auth: "secret" },
      {
        name: "Create an add-on",
        method: "POST",
        path: `${app}/addons`,
        auth: "secret",
        body: { id: "{{addonId}}", name: "Priority support", description: "Replies within 4 hours." },
      },
      { name: "Get an add-on", method: "GET", path: `${app}/addons/:addonId`, auth: "secret" },
      { name: "Update an add-on", method: "PATCH", path: `${app}/addons/:addonId`, auth: "secret", body: { description: "Replies within 2 hours." } },
    ],
  },
  {
    name: "Incentives",
    description: "Per-account overrides on top of the plan: higher limits, extra entitlements and add-ons.",
    requests: [
      { name: "List incentives", method: "GET", path: `${app}/incentives`, auth: "secret" },
      {
        name: "Create an incentive",
        method: "POST",
        path: `${app}/incentives`,
        auth: "secret",
        description: "Add limits and add-ons here too (entitlements: [{ id, max }], addons: [id]), or attach them with the requests below.",
        body: { id: "{{incentiveId}}", name: "Launch boost", description: "Double posts for early users" },
      },
      { name: "Get an incentive", method: "GET", path: `${app}/incentives/:incentiveId`, auth: "secret" },
      { name: "Update an incentive", method: "PATCH", path: `${app}/incentives/:incentiveId`, auth: "secret", body: { name: "Launch boost 2x" } },
      {
        name: "Add an entitlement override",
        method: "POST",
        path: `${app}/incentives/:incentiveId/entitlements`,
        auth: "secret",
        body: { id: "{{entitlementId}}", max: 500 },
      },
      {
        name: "Change an override's limit",
        method: "PATCH",
        path: `${app}/incentives/:incentiveId/entitlements/:entitlementId`,
        auth: "secret",
        body: { max: 1000 },
      },
      { name: "Remove an override", method: "DELETE", path: `${app}/incentives/:incentiveId/entitlements/:entitlementId`, auth: "secret" },
      { name: "Add an add-on", method: "POST", path: `${app}/incentives/:incentiveId/addons`, auth: "secret", body: { id: "{{addonId}}" } },
      { name: "Remove an add-on", method: "DELETE", path: `${app}/incentives/:incentiveId/addons/:addonId`, auth: "secret" },
    ],
  },
  {
    name: "Plans",
    description: "Bundles of entitlements and add-ons, with pricing.",
    requests: [
      { name: "List plans", method: "GET", path: `${app}/plans`, auth: "secret" },
      { name: "Pricing cards", method: "GET", path: `${app}/plans/pricing`, auth: "public", description: `For a pricing table. ${KEYS.public}` },
      {
        name: "Create a plan",
        method: "POST",
        path: `${app}/plans`,
        auth: "secret",
        description: "Ids are normalized: lowercase, spaces to underscores. 409 after Quickstart, which already created Pro.",
        body: {
          id: "{{planId}}",
          name: "Pro",
          description: "For growing teams",
          pricingCard: {
            title: "Pro",
            type: "subscription",
            monthlyPrice: 29,
            yearlyPrice: 290,
            currency: "USD",
            featured: true,
            benefits: [{ id: "posts", title: "100 posts" }],
          },
        },
      },
      { name: "Get a plan", method: "GET", path: `${app}/plans/:planId`, auth: "secret" },
      {
        name: "Update a plan",
        method: "PATCH",
        path: `${app}/plans/:planId`,
        auth: "secret",
        body: { description: "For growing teams", privateMetaKeys: ["stripe_price"] },
      },
      { name: "Get a plan's pricing card", method: "GET", path: `${app}/plans/:planId/pricing`, auth: "public", description: KEYS.public },
      {
        name: "Merge plan meta",
        method: "PATCH",
        path: `${app}/plans/:planId/meta`,
        auth: "secret",
        body: { color: "green", stripe_price: "price_123" },
      },
      {
        name: "Accounts on a plan",
        method: "GET",
        path: `${app}/plans/:planId/namespaces`,
        auth: "secret",
        query: [
          { key: "page", value: "1" },
          { key: "per_page", value: "25" },
        ],
      },
      { name: "Detach an entitlement", method: "DELETE", path: `${app}/plans/:planId/entitlements/:entitlementId`, auth: "secret" },
      {
        name: "Attach an entitlement",
        method: "POST",
        path: `${app}/plans/:planId/entitlements`,
        auth: "secret",
        description: "max: null means unlimited.",
        body: { id: "{{entitlementId}}", max: 100 },
      },
      {
        name: "Change an entitlement's limit",
        method: "PATCH",
        path: `${app}/plans/:planId/entitlements/:entitlementId`,
        auth: "secret",
        body: { max: 250 },
      },
      { name: "Attach an add-on", method: "POST", path: `${app}/plans/:planId/addons`, auth: "secret", body: { id: "{{addonId}}" } },
      { name: "Detach an add-on", method: "DELETE", path: `${app}/plans/:planId/addons/:addonId`, auth: "secret" },
      {
        name: "Check out a plan at list price",
        method: "POST",
        path: `${app}/plans/:planId/checkout`,
        auth: "public",
        description: `Needs PayPal connected. Saves the checkout id. ${KEYS.public}`,
        body: {
          interval: "month",
          account: "{{accountId}}",
          return_url: "https://example.com/welcome",
          cancel_url: "https://example.com/pricing",
        },
        save: { checkoutId: "id" },
      },
    ],
  },
  {
    name: "Accounts",
    description: "Your customers, keyed by an id you choose. The API calls them namespaces.",
    requests: [
      {
        name: "Search accounts",
        method: "GET",
        path: `${app}/namespaces`,
        auth: "secret",
        query: [
          { key: "q", value: "ada", description: "Matches id or name" },
          { key: "plan", value: "{{planId}}", disabled: true },
          { key: "incentive", value: "{{incentiveId}}", disabled: true },
          { key: "offer", value: "{{offerId}}", disabled: true },
          { key: "has_incentive", value: "true", disabled: true },
          { key: "page", value: "1" },
          { key: "per_page", value: "25" },
        ],
      },
      { name: "Count accounts", method: "GET", path: `${app}/namespaces/count`, auth: "secret" },
      {
        name: "Accounts with an incentive",
        method: "GET",
        path: `${app}/namespaces/with-incentive`,
        auth: "secret",
        query: [{ key: "incentive", value: "{{incentiveId}}", disabled: true }],
      },
      {
        name: "Create an account",
        method: "POST",
        path: `${app}/namespaces`,
        auth: "secret",
        description: "409 if the id already exists, as it does after Quickstart.",
        body: { id: "{{accountId}}", name: "Ada Lovelace", plan: "{{freePlanId}}" },
      },
      { name: "Get an account", method: "GET", path: account, auth: "secret" },
      {
        name: "Update an account",
        method: "PATCH",
        path: account,
        auth: "secret",
        description: "Merges name, plan, incentive and incentive_expires_at. Changing the plan here skips payment.",
        body: { name: "Ada", incentive: "{{incentiveId}}", incentive_expires_at: "2030-01-01T00:00:00Z" },
      },
      { name: "Remove the incentive", method: "DELETE", path: `${account}/incentive`, auth: "secret" },
      {
        name: "Mint an account token",
        method: "POST",
        path: `${account}/token`,
        auth: "secret",
        description:
          "An act_… token for this one account, for browser flows such as cancelling. Saves it as accountToken. ttl_seconds is 60 to 86400 (default 3600). Secret key only.",
        body: { ttl_seconds: 3600 },
        save: { accountToken: "token" },
      },
      { name: "Get the account's plan", method: "GET", path: `${account}/plan`, auth: "public", description: `Private meta keys removed. ${KEYS.account}` },
      { name: "Get the account's full plan", method: "GET", path: `${account}/full-plan`, auth: "public", description: KEYS.account },
      { name: "Give the account an add-on", method: "POST", path: `${account}/addons`, auth: "secret", body: { id: "{{addonId}}" } },
      { name: "Remove the account's add-on", method: "DELETE", path: `${account}/addons/:addonId`, auth: "secret" },
    ],
  },
  {
    name: "Usage",
    description: `Counters for usage entitlements. A boolean entitlement returns 400. ${KEYS.public}`,
    requests: [
      { name: "All counters", method: "GET", path: `${account}/usage`, auth: "public" },
      { name: "One counter", method: "GET", path: `${account}/usage/:entitlementId`, auth: "public" },
      {
        name: "Add 1",
        method: "POST",
        path: `${account}/usage/:entitlementId/add`,
        auth: "public",
        description: "Returns 402 with an upgrade offer when the entitlement blocks usage past its limit.",
      },
      { name: "Remove 1", method: "POST", path: `${account}/usage/:entitlementId/remove`, auth: "public" },
      {
        name: "Add an amount",
        method: "POST",
        path: `${account}/usage/:entitlementId/amount`,
        auth: "public",
        description: "An integer. Negative amounts subtract.",
        body: { amount: 5 },
      },
    ],
  },
  {
    name: "Offers",
    description:
      "Ways to buy: plans at a price, with an intro discount, extras and order bumps. Publishing and checkout need PayPal connected (see the PayPal folder).",
    requests: [
      { name: "List offers", method: "GET", path: `${app}/offers`, auth: "secret" },
      {
        name: "Create an offer",
        method: "POST",
        path: `${app}/offers`,
        auth: "secret",
        description: "Creates a draft. Shareable offers use id as their slug. For one account, send type: targeted and account_id instead of id.",
        body: {
          id: "{{offerId}}",
          name: "Launch offer",
          copy: { headline: "Half off Pro for 3 months" },
          discount: { percent: 50, cycles: 3 },
          intervals: ["month", "year"],
          plans: [{ plan_id: "{{planId}}", addons: ["{{addonId}}"] }],
          default_plan: "{{planId}}",
          bumps: [
            {
              id: "welcome_call",
              label: "1:1 welcome call",
              price: { amount: 50 },
              grant: { credits: { entitlement: "{{entitlementId}}", amount: 50 } },
            },
          ],
        },
      },
      {
        name: "Preview an unsaved offer",
        method: "POST",
        path: `${app}/offers/draft-preview`,
        auth: "secret",
        description: "Validates the fields and returns what a checkout page would show. Saves nothing.",
        body: { name: "Spring sale", plans: ["{{planId}}"], discount: { amount_off: 5 }, intervals: ["month"] },
      },
      { name: "Get an offer", method: "GET", path: `${app}/offers/:offerId`, auth: "secret" },
      {
        name: "Update an offer",
        method: "PATCH",
        path: `${app}/offers/:offerId`,
        auth: "secret",
        description: "Applies to future purchases only.",
        body: { max_redemptions: 100, expires_at: "2030-01-01T00:00:00Z" },
      },
      { name: "Publish an offer", method: "POST", path: `${app}/offers/:offerId/publish`, auth: "secret", description: "Creates the PayPal billing plans. 409 without PayPal." },
      {
        name: "Preview what an offer grants",
        method: "POST",
        path: `${app}/offers/:offerId/preview`,
        auth: "secret",
        description: "With account, also shows what would change for that account.",
        body: { account: "{{accountId}}" },
      },
      { name: "Offer stats", method: "GET", path: `${app}/offers/:offerId/stats`, auth: "secret" },
      {
        name: "Public offer for a checkout page",
        method: "GET",
        path: `${app}/offers/:offerId/public`,
        auth: "public",
        description: `What a checkout page shows, with PayPal's client id. Never 404s: falls back to fallback, then to list prices. ${KEYS.public}`,
        query: [
          { key: "fallback", value: "default", disabled: true },
          { key: "account", value: "{{accountId}}", disabled: true },
          { key: "ref", value: "newsletter", disabled: true },
        ],
      },
      {
        name: "Start a checkout",
        method: "POST",
        path: `${app}/offers/:offerId/checkout`,
        auth: "public",
        description: `The API prices the selection from the stored offer and creates the PayPal subscription or order. Open approve_url to pay in the sandbox. Saves the checkout id. ${KEYS.public}`,
        body: {
          plan: "{{planId}}",
          interval: "month",
          bumps: ["welcome_call"],
          account: "{{accountId}}",
          ref: "newsletter",
          return_url: "https://example.com/welcome",
          cancel_url: "https://example.com/pricing",
        },
        save: { checkoutId: "id" },
      },
      { name: "Archive an offer", method: "POST", path: `${app}/offers/:offerId/archive`, auth: "secret", description: "Stops new purchases. Buyers keep their terms." },
    ],
  },
  {
    name: "Checkouts",
    description: "One attempt to buy through an offer. Start one in the Offers folder.",
    requests: [
      {
        name: "List checkouts",
        method: "GET",
        path: `${app}/checkouts`,
        auth: "secret",
        query: [
          { key: "offer", value: "{{offerId}}", disabled: true },
          { key: "status", value: "completed", disabled: true },
          { key: "limit", value: "50" },
        ],
      },
      { name: "Get a checkout", method: "GET", path: `${app}/checkouts/:checkoutId`, auth: "public", description: KEYS.public },
      {
        name: "Complete a checkout",
        method: "POST",
        path: `${app}/checkouts/:checkoutId/complete`,
        auth: "public",
        description: `Run it after approving the payment in PayPal. Returns status created while PayPal is still activating; send it again. ${KEYS.public}`,
      },
    ],
  },
  {
    name: "Subscriptions",
    description: "An account's paid PayPal subscription. These return 404 until the account has completed a checkout.",
    requests: [
      { name: "Get the subscription", method: "GET", path: `${account}/subscription`, auth: "secret", description: KEYS.token },
      {
        name: "Change plan",
        method: "POST",
        path: `${account}/subscription/change`,
        auth: "secret",
        description: "Returns PayPal's approve_url. The change applies once PayPal reports it.",
        body: { plan: "{{planId}}", interval: "year", return_url: "https://example.com/account", cancel_url: "https://example.com/account" },
      },
      { name: "Sync from PayPal", method: "POST", path: `${account}/subscription/sync`, auth: "secret" },
      {
        name: "Pause",
        method: "POST",
        path: `${account}/subscription/pause`,
        auth: "secret",
        description: "Suspends billing for 1 to 12 months and moves the account to the free plan.",
        body: { months: 2, reason: "Taking a break" },
      },
      { name: "Resume", method: "POST", path: `${account}/subscription/resume`, auth: "secret" },
      {
        name: "Cancel",
        method: "POST",
        path: `${account}/subscription/cancel`,
        auth: "secret",
        description: "Cancels in PayPal and moves the account to the free plan.",
        body: { reason: "Too expensive" },
      },
    ],
  },
  {
    name: "PayPal",
    description: "Each app connects its own PayPal REST app. Use sandbox credentials from developer.paypal.com.",
    requests: [
      { name: "Connection status", method: "GET", path: `${app}/paypal`, auth: "secret" },
      {
        name: "Connect PayPal",
        method: "PUT",
        path: `${app}/paypal`,
        auth: "secret",
        description:
          "Checks the credentials with PayPal and stores the secret encrypted. Registers PayPal's webhook when the API has a public HTTPS PUBLIC_API_URL.",
        body: { client_id: "{{paypalClientId}}", client_secret: "{{paypalClientSecret}}", env: "sandbox" },
      },
      {
        name: "PayPal webhook (sent by PayPal)",
        method: "POST",
        path: "/paypal/webhooks/:appId",
        auth: "none",
        description:
          "PayPal posts here. Every delivery is verified with PayPal's verify-webhook-signature API, so a request sent from Postman is rejected. Included so the collection lists every route.",
        body: { id: "WH-EXAMPLE", event_type: "BILLING.SUBSCRIPTION.ACTIVATED", resource: { id: "I-EXAMPLE" } },
      },
    ],
  },
  {
    name: "Cancel flows",
    description: "The steps, questions and save offers a customer sees when they cancel.",
    requests: [
      { name: "List flows", method: "GET", path: `${app}/cancel-flows`, auth: "secret" },
      {
        name: "Capabilities",
        method: "GET",
        path: `${app}/cancel-flows/capabilities`,
        auth: "secret",
        description: "Whether dynamic save offers (ANTHROPIC_API_KEY) and workflow pauses (RENDER_API_KEY) are configured.",
      },
      {
        name: "Create a flow from the template",
        method: "POST",
        path: `${app}/cancel-flows`,
        auth: "secret",
        description: "An empty body creates the default flow from the built-in template: a reason question, a save offer and a confirm step.",
        body: {},
        save: { flowId: "id" },
      },
      { name: "Get a flow", method: "GET", path: `${app}/cancel-flows/:flowId`, auth: "secret" },
      {
        name: "Update a flow",
        method: "PATCH",
        path: `${app}/cancel-flows/:flowId`,
        auth: "secret",
        description: "status is active or draft. steps replaces the whole list.",
        body: { name: "Default cancel flow", status: "active" },
      },
      {
        name: "Flow stats",
        method: "GET",
        path: `${app}/cancel-flows/:flowId/stats`,
        auth: "secret",
        query: [{ key: "days", value: "30" }],
      },
      {
        name: "Preview the save offer",
        method: "POST",
        path: `${app}/cancel-flows/:flowId/preview-offer`,
        auth: "secret",
        description: "The offer a customer would get for these answers. dynamic: true asks Claude when the API has a key.",
        body: { account: "{{accountId}}", answers: ["too_expensive"], dynamic: false },
      },
    ],
  },
  {
    name: "Cancel sessions",
    description:
      "One customer going through a flow, as the SDK runs it: with the account token from Accounts → Mint an account token. Every call returns the session view.",
    requests: [
      {
        name: "Start a session",
        method: "POST",
        path: `${app}/cancel-sessions`,
        auth: "token",
        description: `With a token, the account comes from the token. With the secret key, send account. ${KEYS.token}`,
        body: { flow: "{{flowId}}" },
        save: { sessionId: "id" },
      },
      {
        name: "List sessions",
        method: "GET",
        path: `${app}/cancel-sessions`,
        auth: "secret",
        description: "Secret key only.",
        query: [
          { key: "flow", value: "{{flowId}}", disabled: true },
          { key: "account", value: "{{accountId}}", disabled: true },
          { key: "status", value: "saved", disabled: true },
          { key: "limit", value: "50" },
        ],
      },
      { name: "Get a session", method: "GET", path: `${app}/cancel-sessions/:sessionId`, auth: "token" },
      {
        name: "Answer the reason question",
        method: "POST",
        path: `${app}/cancel-sessions/:sessionId/answer`,
        auth: "token",
        description: "step and answer ids come from the flow. The template's reason step answers include too_expensive, not_using and temporary.",
        body: { step: "reason", answer: "too_expensive" },
      },
      {
        name: "Accept the save offer",
        method: "POST",
        path: `${app}/cancel-sessions/:sessionId/accept`,
        auth: "token",
        description: "Discounts and downgrades return approve_url for PayPal. Needs a PayPal subscription on the account.",
        body: { return_url: "https://example.com/account", cancel_url: "https://example.com/account" },
      },
      { name: "Decline the save offer", method: "POST", path: `${app}/cancel-sessions/:sessionId/decline`, auth: "token" },
      { name: "Go back", method: "POST", path: `${app}/cancel-sessions/:sessionId/back`, auth: "token" },
      { name: "Confirm cancellation", method: "POST", path: `${app}/cancel-sessions/:sessionId/cancel`, auth: "token" },
      { name: "Close (abandon) a session", method: "POST", path: `${app}/cancel-sessions/:sessionId/close`, auth: "token" },
    ],
  },
  {
    name: "Analytics",
    description: "Aggregates of recorded usage. interval is 7d, 30d, 60d, 6m, year or alltime.",
    requests: [
      {
        name: "Usage summary",
        method: "GET",
        path: `${app}/analytics`,
        auth: "secret",
        query: [
          { key: "interval", value: "30d", description: "Required" },
          { key: "namespace", value: "{{accountId}}", disabled: true },
        ],
      },
      {
        name: "Top accounts",
        method: "GET",
        path: `${app}/analytics/top-namespaces`,
        auth: "secret",
        query: [
          { key: "interval", value: "30d" },
          { key: "limit", value: "10" },
          { key: "entitlement", value: "{{entitlementId}}", disabled: true },
        ],
      },
      {
        name: "Time series",
        method: "GET",
        path: `${app}/analytics/timeseries`,
        auth: "secret",
        description: "Daily buckets up to 60 days, weekly beyond.",
        query: [
          { key: "interval", value: "30d" },
          { key: "namespace", value: "{{accountId}}", disabled: true },
          { key: "entitlement", value: "{{entitlementId}}", disabled: true },
        ],
      },
      {
        name: "Usage events",
        method: "GET",
        path: `${app}/analytics/events`,
        auth: "secret",
        query: [
          { key: "namespace", value: "{{accountId}}", disabled: true },
          { key: "entitlement", value: "{{entitlementId}}", disabled: true },
          { key: "limit", value: "50" },
        ],
      },
      { name: "List saved reports", method: "GET", path: `${app}/analytics/reports`, auth: "secret" },
      {
        name: "Save a report",
        method: "POST",
        path: `${app}/analytics/reports`,
        auth: "secret",
        body: { name: "Posts this month", entitlements: ["{{entitlementId}}"], interval: "30d" },
        save: { reportId: "id" },
      },
      { name: "Get a report", method: "GET", path: `${app}/analytics/reports/:id`, auth: "secret" },
      { name: "Update a report", method: "PATCH", path: `${app}/analytics/reports/:id`, auth: "secret", body: { name: "Posts, last 60 days", interval: "60d" } },
    ],
  },
  {
    name: "Webhooks and events",
    description: "Endpoints that receive signed events (Standard Webhooks), their delivery logs, and the app's event log.",
    requests: [
      { name: "List endpoints", method: "GET", path: `${app}/webhooks`, auth: "secret" },
      {
        name: "Add an endpoint",
        method: "POST",
        path: `${app}/webhooks`,
        auth: "secret",
        description: 'Up to 25 per app. events: ["*"] subscribes to everything. Use a public URL, such as one from webhook.site. Saves the endpoint id.',
        body: { url: "{{webhookUrl}}", events: ["*"], description: "From Postman" },
        save: { webhookId: "id" },
      },
      { name: "Get an endpoint", method: "GET", path: `${app}/webhooks/:webhookId`, auth: "secret", description: "Includes the signing secret." },
      {
        name: "Update an endpoint",
        method: "PATCH",
        path: `${app}/webhooks/:webhookId`,
        auth: "secret",
        body: { events: ["account.plan_changed", "usage.limit_reached", "checkout.completed"], enabled: true },
      },
      { name: "Rotate the signing secret", method: "POST", path: `${app}/webhooks/:webhookId/secret/regenerate`, auth: "secret" },
      {
        name: "Send a test event",
        method: "POST",
        path: `${app}/webhooks/:webhookId/test`,
        auth: "secret",
        description: "Sends a sample event once and returns the delivery. Saves its id.",
        body: { type: "account.created" },
        save: { deliveryId: "id" },
      },
      {
        name: "Delivery log",
        method: "GET",
        path: `${app}/webhooks/:webhookId/deliveries`,
        auth: "secret",
        query: [
          { key: "status", value: "failed", disabled: true },
          { key: "limit", value: "50" },
        ],
      },
      { name: "Retry a delivery", method: "POST", path: `${app}/webhooks/:webhookId/deliveries/:deliveryId/retry`, auth: "secret" },
      {
        name: "Event log",
        method: "GET",
        path: `${app}/events`,
        auth: "secret",
        description: "The last 30 days, newest first.",
        query: [
          { key: "type", value: "account.plan_changed", disabled: true },
          { key: "limit", value: "50" },
        ],
      },
    ],
  },
  {
    name: "Admin",
    description:
      "Routes the dashboard and the Render Workflow call. They need the admin key ({{adminKey}}, the API's ADMIN_API_KEY). Locally it is dev-admin-key.",
    requests: [
      { name: "List workspaces", method: "GET", path: "/orgs", auth: "admin" },
      { name: "Create a workspace record", method: "POST", path: "/orgs", auth: "admin", body: { id: "{{orgId}}", app_ids: ["{{appId}}"] } },
      { name: "Get a workspace", method: "GET", path: "/orgs/:orgId", auth: "admin" },
      { name: "Update a workspace's apps", method: "PATCH", path: "/orgs/:orgId", auth: "admin", body: { app_ids: ["{{appId}}"] } },
      { name: "A workspace's apps", method: "GET", path: "/orgs/:orgId/apps", auth: "admin" },
      {
        name: "Import history",
        method: "POST",
        path: `${app}/import`,
        auth: "admin",
        description: "Backdates accounts and usage, up to 10,000 of each per request. No webhooks fire. operation is add, remove or amount.",
        body: {
          namespaces: [{ id: "{{accountId}}", created_at: "2026-01-15T00:00:00Z" }],
          usage_events: [
            { namespace_id: "{{accountId}}", entitlement_id: "{{entitlementId}}", operation: "add", amount: 1, created_at: "2026-02-01T12:00:00Z" },
          ],
        },
      },
      { name: "Pauses due to resume", method: "GET", path: "/pauses/due", auth: "admin", query: [{ key: "limit", value: "100" }] },
      {
        name: "Apply a pause",
        method: "POST",
        path: "/pauses/apply",
        auth: "admin",
        description: "What the pause-subscription workflow task calls.",
        body: { app_id: "{{appId}}", account_id: "{{accountId}}", months: 2, reason: "Taking a break" },
      },
      {
        name: "Resume a pause",
        method: "POST",
        path: "/pauses/resume",
        auth: "admin",
        description: "What the resume-subscription workflow task calls.",
        body: { app_id: "{{appId}}", account_id: "{{accountId}}" },
      },
      {
        name: "Agent threads for a user",
        method: "GET",
        path: `${app}/agent/threads`,
        auth: "admin",
        description: "The dashboard agent's chats.",
        query: [
          { key: "user_id", value: "{{userId}}", description: "Required" },
          { key: "limit", value: "50" },
        ],
      },
      {
        name: "Save a thread",
        method: "PUT",
        path: `${app}/agent/threads/:threadId`,
        auth: "admin",
        description: "Creates the thread or replaces its messages. A thread never changes owner.",
        body: { user_id: "{{userId}}", title: "From Postman", messages: [] },
      },
      { name: "Get a thread", method: "GET", path: `${app}/agent/threads/:threadId`, auth: "admin" },
      { name: "Rename a thread", method: "PATCH", path: `${app}/agent/threads/:threadId`, auth: "admin", body: { title: "Renamed from Postman" } },
    ],
  },
  {
    name: "Clean up",
    description:
      "Deletes what the other folders created, in an order that works, ending with the app itself. Run it last, or skip it to keep the data.",
    requests: [
      { name: "Delete the agent thread", method: "DELETE", path: `${app}/agent/threads/:threadId`, auth: "admin" },
      { name: "Delete the workspace record", method: "DELETE", path: "/orgs/:orgId", auth: "admin", description: "Its apps stay." },
      { name: "Delete the webhook endpoint", method: "DELETE", path: `${app}/webhooks/:webhookId`, auth: "secret", description: "Also deletes its deliveries." },
      { name: "Delete the report", method: "DELETE", path: `${app}/analytics/reports/:id`, auth: "secret" },
      { name: "Delete the cancel flow", method: "DELETE", path: `${app}/cancel-flows/:flowId`, auth: "secret" },
      { name: "Delete the offer", method: "DELETE", path: `${app}/offers/:offerId`, auth: "secret", description: "Buyers keep their price and extras." },
      {
        name: "Delete the account",
        method: "DELETE",
        path: account,
        auth: "secret",
        description: "Resets its usage counters. Analytics events stay.",
      },
      { name: "Delete the incentive", method: "DELETE", path: `${app}/incentives/:incentiveId`, auth: "secret" },
      { name: "Delete the Pro plan", method: "DELETE", path: `${app}/plans/:planId`, auth: "secret" },
      { name: "Delete the Free plan", method: "DELETE", path: `${app}/plans/:planId`, params: { planId: "{{freePlanId}}" }, auth: "secret" },
      { name: "Delete the add-on", method: "DELETE", path: `${app}/addons/:addonId`, auth: "secret" },
      { name: "Delete the entitlement", method: "DELETE", path: `${app}/entitlements/:entitlementId`, auth: "secret" },
      { name: "Disconnect PayPal", method: "DELETE", path: `${app}/paypal`, auth: "secret", description: "404 when PayPal was never connected. Existing subscriptions keep billing." },
      { name: "Delete the app", method: "DELETE", path: app, auth: "secret", description: "Deletes the app and anything left in it." },
    ],
  }
];

/** Collection variables and their starting values. Scripts overwrite the ids and keys as you go. */
export const VARIABLES: { key: string; value: string; description: string }[] = [
  { key: "baseUrl", value: "http://localhost:6767", description: "The Offer API. Override it with an environment for a deployed API." },
  { key: "adminKey", value: "dev-admin-key", description: "The API's ADMIN_API_KEY. dev-admin-key is the local default." },
  { key: "appId", value: "", description: "Saved by Create an app." },
  { key: "secretKey", value: "", description: "The app's secret key (key_…). Saved by Create an app." },
  { key: "publicKey", value: "", description: "The app's publishable key (pub_…). Saved by Create an app." },
  { key: "accountToken", value: "", description: "An act_… token. Saved by Accounts → Mint an account token." },
  { key: "accountId", value: "user_42", description: "The account the requests act on." },
  { key: "freePlanId", value: "free", description: "The free plan." },
  { key: "planId", value: "pro", description: "The paid plan." },
  { key: "entitlementId", value: "posts", description: "A usage entitlement." },
  { key: "addonId", value: "priority_support", description: "An add-on." },
  { key: "incentiveId", value: "launch_boost", description: "An incentive." },
  { key: "offerId", value: "launch", description: "A shareable offer's id." },
  { key: "checkoutId", value: "", description: "Saved by Start a checkout." },
  { key: "flowId", value: "default", description: "A cancel flow. The template creates default." },
  { key: "sessionId", value: "", description: "Saved by Start a session." },
  { key: "reportId", value: "", description: "Saved by Save a report." },
  { key: "webhookId", value: "", description: "Saved by Add an endpoint." },
  { key: "deliveryId", value: "", description: "Saved by Send a test event." },
  { key: "webhookUrl", value: "https://example.com/offer-webhooks", description: "Where test endpoints point. Use your own receiver, such as webhook.site." },
  { key: "paypalClientId", value: "", description: "A PayPal sandbox REST app's client id." },
  { key: "paypalClientSecret", value: "", description: "That app's secret." },
  { key: "orgId", value: "postman_workspace", description: "A dashboard workspace id." },
  { key: "userId", value: "postman_user", description: "A dashboard user id, for agent threads." },
  { key: "threadId", value: "postman_thread", description: "An agent thread id." },
];
