import type { Metadata } from "next";
import Link from "next/link";
import { Callout, DocsHeader, H2, Table } from "@/components/docs/prose";

export const metadata: Metadata = {
  title: "Environment variables",
  description: "Every environment variable the API, dashboard and Workflows service read, with defaults and what the Blueprint sets.",
};

export default function EnvironmentPage() {
  return (
    <>
      <DocsHeader
        title="Environment variables"
        lead="Every variable each service reads. Locally none of them are required. On Render, the Blueprint sets or asks for the ones that matter."
      />

      <p>
        In development (<code>next dev</code> for the dashboard, any <code>NODE_ENV</code> other than production or
        test for the API), each service fills in local defaults so they find each other with no <code>.env</code>{" "}
        files. Production and tests get no defaults. To override a value locally, copy{" "}
        <code>api/.env.example</code> to <code>api/.env</code> or <code>offer-app/.env.example</code> to{" "}
        <code>offer-app/.env.local</code>.
      </p>

      <H2>API</H2>
      <p>
        Service <strong>offersdk-api</strong>, code in <code>api/</code>.
      </p>
      <Table
        head={["Variable", "Default", "Description"]}
        rows={[
          [
            "DATABASE_URL",
            <>
              Dev: local Postgres
            </>,
            "Postgres connection string. The Blueprint uses the database's internal URL.",
          ],
          ["ADMIN_API_KEY", <>Dev: <code>dev-admin-key</code></>, "Full-access key. The dashboard and the Workflows service use the same value. You set it."],
          ["BETTER_AUTH_SECRET", "Dev fallback", "Signs dashboard sessions. Required in production. Generated by the Blueprint."],
          ["APP_URL", <code key="c">http://localhost:6768</code>, "The dashboard's public URL. Sessions are issued for it and only its origin is trusted."],
          [
            "PUBLIC_API_URL",
            <>
              On Render: <code>RENDER_EXTERNAL_URL</code>
            </>,
            "This API's public HTTPS URL. PayPal webhooks are registered under it when an app connects PayPal. Set it for a custom domain, or when the API runs outside Render.",
          ],
          [
            "SECRETS_KEY",
            <>
              <code>BETTER_AUTH_SECRET</code>, then <code>ADMIN_API_KEY</code>
            </>,
            "Encrypts stored PayPal client secrets.",
          ],
          ["ANTHROPIC_API_KEY", "None", "Turns on dynamic save offers in cancel flows. Without it, flows use their static offer."],
          ["DECIDE_MODEL", <code key="c">claude-opus-5-5</code>, "Model that picks dynamic save offers."],
          ["DECIDE_TIMEOUT_MS", <code key="c">20000</code>, "How long to wait for the model before falling back to the static offer."],
          ["RENDER_API_KEY", "None", "With RENDER_WORKFLOW_SLUG, runs pauses as Render Workflow tasks."],
          [
            "RENDER_WORKFLOW_SLUG",
            "None",
            <>
              The Workflows service to start tasks on. The Blueprint sets <code>offersdk-workflows</code>.
            </>,
          ],
          ["PORT", <>3000, dev: 6767</>, "Port to listen on."],
          ["MIGRATE_ON_BOOT", <code key="c">true</code>, <>Set to <code>false</code> to run <code>bun run migrate</code> yourself.</>],
          ["DATABASE_POOL_MAX", <code key="c">10</code>, "Postgres pool size for the API."],
          ["AUTH_DATABASE_POOL_MAX", <code key="c">5</code>, "Postgres pool size for dashboard sign-in."],
          ["WEBHOOKS_WORKER", <code key="c">true</code>, <>Set to <code>false</code> to not deliver webhooks from this instance.</>],
          [
            "WEBHOOKS_ALLOW_PRIVATE_URLS",
            <>
              <code>false</code>, dev: <code>true</code>
            </>,
            "Allows webhook endpoints on localhost and private networks. Development only.",
          ],
          ["PAUSE_WORKER", <code key="c">true</code>, <>Set to <code>false</code> to stop this instance checking for pauses that are due.</>],
          [
            "PAUSE_WORKER_INTERVAL_MS",
            "10 min, or 60 min with Workflows",
            "How often the API checks for pauses that are due.",
          ],
          ["PAYPAL_API_URL", "PayPal's sandbox or live URL", "Sends every PayPal call to another base URL. The tests use it for a fake PayPal."],
        ]}
      />
      <Callout tone="warning" title="Changing the encryption secret disconnects PayPal.">
        Stored PayPal secrets are encrypted with <code>SECRETS_KEY</code>, or with <code>BETTER_AUTH_SECRET</code> when
        it isn&apos;t set. If that value changes, the API can no longer read them and every app has to connect PayPal
        again. Set <code>SECRETS_KEY</code> on its own if you expect to rotate the auth secret.
      </Callout>

      <H2>Dashboard</H2>
      <p>
        Service <strong>offer-app</strong>, code in <code>offer-app/</code>.
      </p>
      <Table
        head={["Variable", "Default", "Description"]}
        rows={[
          [
            "OFFER_API_URL",
            <>
              Dev: <code>http://localhost:6767</code>
            </>,
            <>
              The API&apos;s public URL, shown in snippets. <code>mock</code> uses the built-in mock API. Unset outside
              development also means the mock.
            </>,
          ],
          [
            "OFFER_API_ADMIN_KEY",
            <>
              Dev: <code>dev-admin-key</code>
            </>,
            <>
              The API&apos;s <code>ADMIN_API_KEY</code>. Required whenever <code>OFFER_API_URL</code> is set.
            </>,
          ],
          [
            "OFFER_API_INTERNAL_URL",
            "None",
            <>
              A private address for server-to-server calls, such as <code>offersdk-api:10000</code>. Wired by the
              Blueprint.
            </>,
          ],
          ["ANTHROPIC_API_KEY", "None", "Turns on the Agent page."],
          [
            "AGENT_APPROVAL_SECRET",
            "Derived from another secret",
            "Signs the agent's change approvals. Set the same value on every instance if you run more than one.",
          ],
          [
            "DEMO_ENABLED",
            <>
              Dev: <code>true</code>
            </>,
            <>
              Shows <strong>Explore the demo workspace</strong> on the sign-in page. The first click builds the demo
              workspace. The Blueprint sets <code>true</code>.
            </>,
          ],
          [
            "CORS_ORIGINS",
            <code key="c">*</code>,
            "Origins allowed to call the dashboard's public routes from the browser. A comma-separated list, or * for any.",
          ],
          ["DEMO_APP_ID", "None", "App for the public PayPal checkout demo at /demo/checkout."],
          ["DEMO_PUBLISHABLE_KEY", "None", "That app's publishable key."],
          ["BETTER_AUTH_SECRET", "None", "Mock mode only, where sign-in runs inside the dashboard."],
          ["BETTER_AUTH_URL", "None", "Mock mode only. The dashboard's own URL."],
        ]}
      />

      <H2>Workflows</H2>
      <p>
        Service <strong>offersdk-workflows</strong>, code in <code>workflows/</code>.
      </p>
      <Table
        head={["Variable", "Description"]}
        rows={[
          ["OFFER_API_URL", "The API's public URL. The tasks call its admin-only /pauses routes. You set it."],
          ["ADMIN_API_KEY", "Copied from the API by the Blueprint."],
        ]}
      />

      <H2>Marketing site</H2>
      <Table
        head={["Variable", "Description"]}
        rows={[
          [
            "NEXT_PUBLIC_APP_URL",
            <>
              The dashboard&apos;s URL, used by the site&apos;s sign-in and demo links. Defaults to{" "}
              <code>http://localhost:6768</code>.
            </>,
          ],
        ]}
      />

      <H2>Scripts</H2>
      <p>
        <code>pnpm seed:demo</code> reads <code>APP_URL</code>, the dashboard whose demo workspace it builds (or rebuilds
        with <code>--reset</code>), and defaults to <code>http://localhost:6768</code>. See{" "}
        <Link href="/docs/deploy">Deploy on Render</Link> for resetting a deployed dashboard&apos;s demo.
      </p>
    </>
  );
}
